### ISSUE TITLE
Persist download status

### ISSUE THREAD

**Issue by johngully** [johngully/overdrive-download#19]
When the web interface is refreshed, the historical download status is removed. Saving the fact that a download completed (in a cookie) would help users remember if a title had been downloaded.

**Comment by fivestones** [comment]
I agree, this would be great.

**Comment by johngully** [comment]
Added cache of the download status of books that works across user sessions. This means that books that have been successfully downloaded will display a green download button (to signify a successful download), rather than the blue download button that is displayed prior to download.
